name: PMO
favicon: null
layout_spectrum: 0.6509047523140907
typography_spectrum: 0.7087761166039854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#88abbc'
    - '#ffffff'
    - '#596271'
    - '#f2bb67'
    - '#f3835d'
  brandStrength: 0.31573287304490805
  lightness: 0.6194649192038924
  saturation: 0.969766422174871
  rhythmicContrast: 0.8905666850041598
purpose: []
